######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 22 16:43:23 2007
######################################################################

TEMPLATE = subdirs
CONFIG += debug
# Directories
SUBDIRS += engine qsculpt enginetest enginetestapp
#SUBDIRS += enginetestapp
