######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 22 16:43:23 2007
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += engine qsculpt
